### ISSUE TITLE
Hacer reto Zara - 8:00h?

### ISSUE THREAD

**Issue by helion1** [helion1/Vueling#43]

**Comment by helion1** [comment]
REAL: 11H

**Comment by jordiascension** [comment]
El fichero csv debe de estar dentro del proyecto y lo tengo que ver en el Git. Tampoco veo el README donde explicas como has realizado el reto Zara.

**Comment by helion1** [comment]
Cierto! Fallo mío lo del .csv! 
Estaba haciendo lo del SOLID y se me ha ido de la cabeza jaja! 
Te lo hago en cuanto pueda antes de mañana a las 15:00!
